name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Include submodule during checkout
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: test prompt2model
        run: pytest -v
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Include submodule during checkout
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: format
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: black --all-files
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Include submodule during checkout
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: isort
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: isort --all-files
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Include submodule during checkout
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: flake8 --all-files
      - name: lint-pep585-compliant
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: upgrade-type-hints --all-files
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Include submodule during checkout
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: mypy
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: mypy --all-files
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Include submodule during checkout
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: markdownlint-cli2 --all-files
